### ISSUE TITLE
Not sure how to get registration matrix

### ISSUE THREAD

**Issue by DylanHsu** [alanqrwang/brainmorph#3]
Hi Alan,
Firstly, thank you for this great work. I apologize if my question is stupid, but I am trying to figure out how to obtain the 4x4 transformation matrix for the rigid or affine transformation determined by the registration model. This matrix is necessary in order to create a Dicom registration file or an ITK transform file. Is there a way to read it out from the outputs which are created by the registration script? If not, I am interested to work on a small pull request, when I have time.
Cheers, Dylan

**Comment by alanqrwang** [comment]
Hi Dylan,

Thanks for the question. I've pushed a new commit so that the script now saves the matrix for rigid/affine transformations. I've also updated the colab tutorial so you can see how to load it. Let me know if there's any issues/suggestions!

Best,
Alan

**Comment by DylanHsu** [comment]
Hi, I pulled the latest version of main and tried to run affine and rigid methods. Unfortunately I get "Matrix is None" error for both. I tried to debug by showing the contents of `res_dict` and the matrix is not in there for some reason. It's probably not related, but I am running this on windows 10. I don't think I need to download updated weights, right? Here is the command I tried this morning:

`python scripts\register.py --num_keypoints 512 --variant L --weights_dir D:\dylan\keymorph_weights --moving D:\dylan\testNiftyReg\MR1_2017-04-08.nii.gz --fixed D:\dylan\testNiftyReg\MR6_2018-05-17.nii.gz --list_of_aligns rigid affine --save_eval_to_disk --save_dir D:\dylan\testNiftyReg\testBrainMorphSave --gpus 0`

I will keep looking into it when I have time.

p.s. There was a small fix I had to do for unpickling the model weights on Windows, I can submit a small PR for that sometime soon.

**Comment by DylanHsu** [comment]
Sorry for the double post, but it looks like this is because I need the latest version of KeyMorph
https://github.com/alanqrwang/keymorph/commit/983ffcfc160f9ec02dd2cfbeeebe9b675addadfd
For now, I guess I can try to remove KeyMorph v1.0.0 pip package, checkout the master branch of KeyMorph, and add it to my PYTHONPATH.

**Comment by alanqrwang** [comment]
Yes, you could also clone the repo and install all dependencies from scratch. Closing for now.
